name: Deploy
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'LICENSE'
      - '*.md'
      - '.github/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4

      - run: pnpm install

      - run: pnpm build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 'language-convert-kit'
          entrypoint: 'https://deno.land/std@0.217.0/http/file_server.ts'
          root: 'dist'
